### ISSUE TITLE
4k@60hz working in Sierra but not outputting via HDMI

### ISSUE THREAD

**Issue by LonnieCoffman** [Floris497/mac-pixel-clock-patch-V2#104]
Not sure that this is an issue with the pixel clock patch or not, but I have seen may issues here related to the patch not working on hackintosh Sierra installs.  Like many others I encounter a black screen after the patch install, although I can blindly login in and hear that the system is loaded.  I decided to blindly open the System Information app, navigate to the Graphics/Displays section and take a screenshot.  Here is what I found:
![image](https://cloud.githubusercontent.com/assets/22034947/20070481/65957488-a4d5-11e6-8bac-c3a03903b8dd.png)
As you can see this is showing 3840x2160 @ 60hz.  I have my display connected via HDMI.  I do not have a display port adapter so I can't try that.

**Comment by Floris497** [comment]
Have you tried the IOKit patch for sierra?

**Comment by LonnieCoffman** [comment]
Reinstalled and tried with IOKit, CoreDisplay and then again with IOKit and CoreDisplay.  No change from any.

**Comment by LonnieCoffman** [comment]
I have connected a display port to HDMI 2.0 adapter and now get 60hz on my Sierra hackintosh.  Worked without using pixel clock patch or switchresx.

**Comment by joevt** [comment]
Which DisplayPort to HDMI 2.0 adapter did you use? Some may be incorrectly limited by Mac OS graphics driver to 30 Hz, but yours is not.

**Comment by LonnieCoffman** [comment]
Club3D Displayport 1.2 to HDMI 2.0 UHD (CAC-1070)

**Comment by joevt** [comment]
I have that one too but no 60 Hz HDMI displays to try it on, and my two different HDMI to DisplayPort adapters (opposite direction than the Club3D adapter) are only 30 Hz.
The Club3D adapter has revision and firmware version numbers:
> CAC-1070
> REV.:A1-00
> FW:7.1E
> 1613

Does your adapter have the same numbers?

In your original post, you said you were trying to connect a display to the HDMI port of a Hackintosh. What is the motherboard? I don't think that matters since you were trying to connect to a GTX 970 graphics card? Which GTX 970 are you using? I think all GTX 970 have HDMI 2.0 so there shouldn't have been a problem. Have you tried the HDMI port on the GTX 970 in Windows or Linux? That could tell you if there is a problem with the Mac drivers which a patch should be able to fix. Well, the readme for this patch says "Enables HDMI2.0 on Nvidia Maxwell cards (Never tested this myself, for this you only need the IOKit patch not the Nvidia patch)"

It's possible that the screen was black, not because of the patch, but because you need to rebuild the kext cache after changing kernel extensions.

```
sudo kextcache -system-prelinked-kernel
sudo kextcache -Boot -U /
sudo kectcache -system-cache
sudo touch /System/Library/Extensions
```

You said you blindly logged in. You should keep screen sharing enabled to handle problems like this on a hackintosh (unless you don't have another Mac to view the screen).

**Comment by LonnieCoffman** [comment]
All of the issues that I had were when I was using HDMI 2.0 from my Asus Strix GTX 970.  My motherboard is a Gigabyte Z170MX Gaming 5.  The HDMI port works fine in Windows and Arch.  I believe the problem is with Nvidia's mac drivers and perhaps a future update will allow HDMI to work.

Prior to switching to the displayport adapter I did a fresh install of Sierra.  After installing the Nvidia driver 60hz worked without the need for any patches or switchresx.
