### ISSUE TITLE
HiDPI 2560 x 1440 is NOT able to display at 60Hz (but 4K @ 60Hz works !)

### ISSUE THREAD

**Issue by diophung** [Floris497/mac-pixel-clock-patch-V2#217]
@Floris497 : 

Model: MacBook Pro (15-inch, 2017)
MacOS Sierra: 10.12.6 
Graphics: Radeon Pro 560 4096 MB, Intel HD Graphics 630 1536 MB

I ran your patches and got 4K @ 60Hz on Sierra 10.12.6 (yay!):

![image](https://user-images.githubusercontent.com/2221178/30254683-0164db70-9651-11e7-9cbd-1f5e88cbe579.png)

but 2560 x 1440 refresh rate is still locked at 30Hz. Any idea?

![image](https://user-images.githubusercontent.com/2221178/30254697-256f9aa0-9651-11e7-8ecf-c2b8f5d61771.png)

**Comment by Floris497** [comment]
SwitchResX custom resolution

**Comment by diophung** [comment]
I tried SwitchResX, but it's not showing anything for HiDpi 2560 x 14440 @60Hz . 

<img width="821" alt="screen shot 2017-09-11 at 3 24 58 pm" src="https://user-images.githubusercontent.com/2221178/30299628-644f7362-9705-11e7-9061-daff0953dfb2.png">

Note there is a non-HiDpi 2560 x 14440 @60Hz (which is blurry because I'm on a 4K monitor).

**Comment by Gaulomatic** [comment]
You need to modify your monitor / TV plist file manually. This is what I did:

1. Patch IOKit
2. Add custom resolution (3840x2160@60) via SwitchResX
3. Find the monitor definition file, in my case /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-4c2d/DisplayYearManufacture-2016-DisplayWeekManufacture-1
4. Go to [this link](https://comsysto.github.io/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions/) add the HiDPI modes you which to have into the web interface and copy&paste the "scale-resolutions" key and the array node below into your monitor definition file.
5. Reboot
6. While in SysPrefs->Display hold down the option key while clicking on "Scaled" to get a full list of possible resolutions instead of the Retina-Five-Button choice. Select your preferred HiDPI mode and select 60 Hz as refresh rate.
7. Enjoy.

Step 3 to 7 should be the ones you are looking for.

**Comment by diophung** [comment]
@Gaulomatic : I followed your steps and use [this link](https://comsysto.github.io/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions/) to generate the plist file, and the problem still persists: I can't select 60Hz as refresh rate.

![image](https://user-images.githubusercontent.com/2221178/30524719-98f657be-9bad-11e7-9911-e490767f92f0.png)

Here are more details about my display:

```
$ ioreg -lw0 | grep IODisplayPrefsKey
    | |   |   | |           "IODisplayPrefsKey" = "Alias:0/AppleBacklightDisplay-610-a030"
    | |   |   | |           "IODisplayPrefsKey" = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG0@1/IOPP/GFX0@0/ATY,Longavi@1/AMDFramebufferVIB/display0/AppleDisplay-2268-3200"
```

and this is my plist file, saved at `/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-2268/DisplayProductID-3200`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>DisplayProductName</key>
  <string>QNIX 4K</string>
  <key>DisplayProductID</key>
  <integer>12800</integer>
  <key>DisplayVendorID</key>
  <integer>8808</integer>
  <key>scale-resolutions</key>
  <array>
    <data>AAAKAAAABaAAAAABACAAAA==</data>
  </array>
</dict>
</plist>
```

**Comment by Floris497** [comment]
Well 2560x1440 in HiDPI is 5120x2880 for the GPU to render.. maybe applying the CoreDisplay patch will help. I was just working on it and was able to make a new patch for 10.13 it should be available soon. for now I'll close this issue. please reopen if you need more help :)

**Comment by joevt** [comment]
There is a new hidden preference in macOS 10.14.6 that enables multiple refresh rates for scaled resolutions.
````
sudo defaults write /Library/Preferences/com.apple.CoreDisplay multiRefreshRateScaledModes -bool true
````

https://www.tonymacx86.com/threads/adding-using-hidpi-custom-resolutions.133254/page-81#post-1999206

**Comment by zhuziyi1989** [comment]
> macOS 10.14.6中有一个新的隐藏首选项，可为缩放分辨率启用多种刷新率。
> 
> ```
> sudo defaults write /Library/Preferences/com.apple.CoreDisplay multiRefreshRateScaledModes -bool true
> ```
> 
> https://www.tonymacx86.com/threads/adding-using-hidpi-custom-resolutions.133254/page-81#post-1999206

thinks.
