### ISSUE TITLE
MAXWELL-patcher explanation

### ISSUE THREAD

**Issue by PMheart** [Floris497/mac-pixel-clock-patch-V2#265]
Hi,

Could you please explain [this line](https://github.com/Floris497/mac-pixel-clock-patch-V2/blob/master/NVIDIA-WEB-MAXWELL-patcher.command#L77)? My [CoreDisplayFixup ("CDF" in context)](https://github.com/PMheart/CoreDisplayFixup/blob/master/CoreDisplayFixup/NVPatcher.cpp#L81) is using exactly the same patch. (Yes! It was actually copied from yours!)
Yet I saw a ["fork"](https://github.com/aerror2/CoreDisplayFixLG5K/blob/master/CoreDisplayFixup/NVPatcher.cpp#L81) of CDF using another replace pattern. The author did it intentionally as written in [README](https://github.com/aerror2/CoreDisplayFixLG5K/blob/master/README.md):
> Fix for LG Ultrafine 5K. change: static const uint8_t gmp100_repl[] = {0x80, 0x1A, 0x06, 0x00 }; TO: static const uint8_t gmp100_repl[] = { 0x40, 0x42, 0x0F, 0x00 };

**Comment by Floris497** [comment]
Ah, so the limited is set to 400MHz max actually it's a static value, taking in regard big/little endian.. (as by original design im using the bytes around the replacement target as well to make sure not at an incorrect place gets replaced)
Anyway, this value can be increased to say 800MHz or whatever value fits in the 4 byte space..

I see you are making some interesting things here with the kext. A great feature would be patching the correct driver for Nvidia, since every chip architecture has its dedicated kext.. same goes for web and non web drivers.

Another thing I haven't been investigating is the influence that IOKit still has on the Nvidia drivers.. there used to be a connection even after code was copied from IOKit to CoreDisplay.. (namely HDMI2.0 speeds, and higher than 300MHz on dual link DVI)

I hope this information was at least somewhat useful for you :)

**Comment by PMheart** [comment]
Hi! Thanks for the clarification!
So, should I use the patch from CDF fork?

**Comment by Floris497** [comment]
I actually didn't check the values (it's 5am), but you could for sure if it's using a higher number

**Comment by PMheart** [comment]
OK! Have a rest then.
